### ISSUE TITLE
`setMaxListeners(Infinity)` call should probably be removed

### ISSUE THREAD

**Issue by huntharo** [fed135/ha-store#116]
**Describe the bug**

The `setMaxListeners(Infinity)` call seems like a hidden bad idea.  Letting EventEmitter print the warning when it goes over 10 listeners may help some consumers find that they were leaking listeners.  It seems that this should just be removed and left to the consumer to raise / disable if they choose.

```js
    if (this.setMaxListeners) {
      this.setMaxListeners(Infinity);
    }
```

https://github.com/fed135/ha-store/blob/c60ea825031af4280d7b863a3f6f6b3566977e68/src/index.js#L22-L24

**To Reproduce**
n/a

**Expected behavior**
Consumer should disable the event emitter listener limit if they choose to do so.

**Additional context**
Thoughts?

**Comment by fed135** [comment]
That's a fair point, I will remove it.
