### ISSUE TITLE
npmjs.org Package Page has no Readme Doc

### ISSUE THREAD

**Issue by huntharo** [fed135/ha-store#117]
**Is your feature request related to a problem? Please describe.**
https://www.npmjs.com/package/ha-store

**Describe the solution you'd like**
I'd like the npmjs.org page to have a README doc describing what the module is.

The silly thing here is that the `README.md` has to be removed from `.npmignore` and included in the package tarball.  It's lame... but it's what most packages are doing and there are tools such as `node-prune` to remove the `.md` files from non-bundled builds if app developer choose to do so.

**Describe alternatives you've considered**
The alternative exists which is to click the link to read the readme, but that doesn't fit the model of most other packages.

**Additional context**
n/a

**Comment by fed135** [comment]
Hmm, I do see README.md present in the .npmignore file, but NPM usually ignores this. 

I'll remove the line. Good catch, we shouldn't omit the README

**Comment by huntharo** [comment]
I think npm ignores the .npmignore when you have a files: in package.json. If you do not have files then it uses the .npmignore. It does not attempt to merge the two. I have wasted hours because of this on other projects :)
